import { useState, useEffect } from 'react'
import { Volume2, Trash2, Loader2, ChevronLeft, ChevronRight, Circle, CheckCircle2 } from 'lucide-react'
import {
  Button,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@donkeywork/ui'
import { tts, type TtsRecording } from '@donkeywork/api-client'
import { AudioPlayer } from '@/components/audio/AudioPlayer'

const PAGE_SIZE = 20

export function RecordingsPage() {
  const [recordings, setRecordings] = useState<TtsRecording[]>([])
  const [totalCount, setTotalCount] = useState(0)
  const [page, setPage] = useState(0)
  const [loading, setLoading] = useState(true)
  const [deleteId, setDeleteId] = useState<string | null>(null)
  const [deleting, setDeleting] = useState(false)
  const [expandedId, setExpandedId] = useState<string | null>(null)

  const loadRecordings = async (offset = 0) => {
    setLoading(true)
    try {
      const response = await tts.listRecordings(offset, PAGE_SIZE)
      setRecordings(response.items)
      setTotalCount(response.totalCount)
    } catch (error) {
      console.error('Failed to load recordings:', error)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadRecordings(page * PAGE_SIZE)
  }, [page])

  const totalPages = Math.ceil(totalCount / PAGE_SIZE)
  const canGoBack = page > 0
  const canGoForward = page < totalPages - 1

  const handleDelete = async () => {
    if (!deleteId) return
    setDeleting(true)
    try {
      await tts.deleteRecording(deleteId)
      if (expandedId === deleteId) setExpandedId(null)
      loadRecordings(page * PAGE_SIZE)
    } catch (error) {
      console.error('Failed to delete recording:', error)
    } finally {
      setDeleting(false)
      setDeleteId(null)
    }
  }

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const formatSize = (bytes: number) => {
    if (bytes < 1024) return `${bytes} B`
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
  }

  return (
    <div className="container mx-auto max-w-5xl space-y-6 p-4 md:p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Listen</h1>
          <p className="text-sm text-muted-foreground">Audio recordings generated by orchestrations</p>
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </div>
      ) : recordings.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <Volume2 className="h-12 w-12 text-muted-foreground/30 mb-4" />
          <h3 className="text-lg font-medium">No recordings yet</h3>
          <p className="text-sm text-muted-foreground mt-1">
            Recordings will appear here when created by orchestrations with TTS and Store Audio nodes.
          </p>
        </div>
      ) : (
        <>
          {/* Mobile cards */}
          <div className="space-y-3 md:hidden">
            {recordings.map((recording) => (
              <div key={recording.id} className="rounded-xl border border-border bg-card p-4 space-y-3">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-2 min-w-0 flex-1">
                    {recording.playback?.completed ? (
                      <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0" />
                    ) : (
                      <Circle className="h-4 w-4 text-pink-500 fill-pink-500 shrink-0" />
                    )}
                    <div className="font-medium truncate">{recording.name}</div>
                    <div className="text-xs text-muted-foreground mt-1">{recording.description}</div>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setDeleteId(recording.id)}
                    className="text-muted-foreground hover:text-destructive shrink-0"
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
                <div className="flex items-center gap-4 text-xs text-muted-foreground">
                  {recording.voice && <span>Voice: {recording.voice}</span>}
                  {recording.model && <span>Model: {recording.model}</span>}
                  <span>{formatSize(recording.sizeBytes)}</span>
                </div>
                <AudioPlayer
                  recordingId={recording.id}
                  name={recording.name}
                  transcript={recording.transcript}
                />
              </div>
            ))}
          </div>

          {/* Desktop table */}
          <div className="hidden md:block rounded-xl border border-border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[40px]" />
                  <TableHead>Name</TableHead>
                  <TableHead>Voice</TableHead>
                  <TableHead>Model</TableHead>
                  <TableHead>Size</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="w-[60px]" />
                </TableRow>
              </TableHeader>
              <TableBody>
                {recordings.map((recording) => (
                  <>
                    <TableRow
                      key={recording.id}
                      className="cursor-pointer"
                      onClick={() => setExpandedId(expandedId === recording.id ? null : recording.id)}
                    >
                      <TableCell className="w-[40px] pr-0">
                        {recording.playback?.completed ? (
                          <CheckCircle2 className="h-4 w-4 text-emerald-500" />
                        ) : (
                          <Circle className="h-4 w-4 text-pink-500 fill-pink-500" />
                        )}
                      </TableCell>
                      <TableCell>
                        <div>
                          <div className="font-medium">{recording.name}</div>
                          <div className="text-xs text-muted-foreground truncate max-w-[300px]">
                            {recording.description}
                          </div>
                        </div>
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">{recording.voice ?? '-'}</TableCell>
                      <TableCell className="text-sm text-muted-foreground">{recording.model ?? '-'}</TableCell>
                      <TableCell className="text-sm text-muted-foreground">{formatSize(recording.sizeBytes)}</TableCell>
                      <TableCell className="text-sm text-muted-foreground">{formatDate(recording.createdAt)}</TableCell>
                      <TableCell>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={(e) => {
                            e.stopPropagation()
                            setDeleteId(recording.id)
                          }}
                          className="text-muted-foreground hover:text-destructive"
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                    {expandedId === recording.id && (
                      <TableRow key={`${recording.id}-player`}>
                        <TableCell colSpan={7} className="p-4">
                          <AudioPlayer
                            recordingId={recording.id}
                            name={recording.name}
                            transcript={recording.transcript}
                          />
                        </TableCell>
                      </TableRow>
                    )}
                  </>
                ))}
              </TableBody>
            </Table>
          </div>

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between">
              <p className="text-sm text-muted-foreground">
                Showing {page * PAGE_SIZE + 1}-{Math.min((page + 1) * PAGE_SIZE, totalCount)} of {totalCount}
              </p>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" disabled={!canGoBack} onClick={() => setPage(p => p - 1)}>
                  <ChevronLeft className="h-4 w-4" />
                  Previous
                </Button>
                <Button variant="outline" size="sm" disabled={!canGoForward} onClick={() => setPage(p => p + 1)}>
                  Next
                  <ChevronRight className="h-4 w-4" />
                </Button>
              </div>
            </div>
          )}
        </>
      )}

      {/* Delete confirmation */}
      <Dialog open={!!deleteId} onOpenChange={() => setDeleteId(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Recording</DialogTitle>
            <DialogDescription>
              This will permanently delete the recording and its audio file. This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteId(null)}>Cancel</Button>
            <Button variant="destructive" onClick={handleDelete} disabled={deleting}>
              {deleting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Delete'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
