apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-silo
  namespace: donkeywork-agents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-silo
  namespace: donkeywork-agents
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-silo
  namespace: donkeywork-agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-silo
subjects:
  - kind: ServiceAccount
    name: api-silo
    namespace: donkeywork-agents
