// <auto-generated />
using System;
using DonkeyWork.Agents.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DonkeyWork.Agents.Persistence.Migrations
{
    [DbContext(typeof(AgentsDbContext))]
    [Migration("20260527100116_RemoveOrchestrationsAndTts")]
    partial class RemoveOrchestrationsAndTts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.A2a.A2aServerConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("address");

                    b.Property<bool>("ConnectToNavi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("connect_to_navi");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_a2a_server_configurations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_a2a_server_configurations_user_id");

                    b.HasIndex("UserId", "IsEnabled")
                        .HasDatabaseName("ix_a2a_server_configurations_user_id_is_enabled");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_a2a_server_configurations_user_id_name");

                    b.ToTable("server_configurations", "a2a");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.A2a.A2aServerHeaderConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("A2aServerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("a2a_server_configuration_id");

                    b.Property<string>("CredentialFieldType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("credential_field_type");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("HeaderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("header_name");

                    b.Property<byte[]>("HeaderValueEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("header_value_encrypted");

                    b.HasKey("Id");

                    b.HasIndex("A2aServerConfigurationId")
                        .HasDatabaseName("ix_a2a_header_configurations_a2a_server_configuration_id");

                    b.HasIndex("A2aServerConfigurationId", "HeaderName")
                        .IsUnique()
                        .HasDatabaseName("ix_a2a_header_configurations_config_id_header_name");

                    b.ToTable("header_configurations", "a2a", t =>
                        {
                            t.HasCheckConstraint("ck_a2a_header_value_or_credential", "(header_value_encrypted IS NOT NULL AND credential_id IS NULL AND credential_field_type IS NULL) OR (header_value_encrypted IS NULL AND credential_id IS NOT NULL AND credential_field_type IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Actors.AgentExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent_type");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContractSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contract_snapshot");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("GrainKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("grain_key");

                    b.Property<string>("Input")
                        .HasColumnType("text")
                        .HasColumnName("input");

                    b.Property<int?>("InputTokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens_used");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_id");

                    b.Property<string>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<int?>("OutputTokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens_used");

                    b.Property<string>("ParentGrainKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("parent_grain_key");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_agent_executions_conversation_id");

                    b.HasIndex("GrainKey")
                        .HasDatabaseName("ix_agent_executions_grain_key");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_agent_executions_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_agent_executions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_agent_executions_user_id");

                    b.HasIndex("ConversationId", "StartedAt")
                        .HasDatabaseName("ix_agent_executions_conversation_id_started_at");

                    b.HasIndex("ConversationId", "TurnId")
                        .HasDatabaseName("ix_agent_executions_conversation_id_turn_id");

                    b.ToTable("agent_executions", "actors");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Actors.GrainCompactionMarkerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AtSequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("at_sequence_number");

                    b.Property<Guid>("AtTurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("at_turn_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GrainKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("grain_key");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_grain_compaction_markers_user_id");

                    b.HasIndex("GrainKey", "AtSequenceNumber")
                        .HasDatabaseName("ix_grain_compaction_markers_grain_key_at_sequence_number");

                    b.ToTable("grain_compaction_markers", "actors");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Actors.GrainMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GrainKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("grain_key");

                    b.Property<string>("MessageJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("message");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_grain_messages_user_id");

                    b.HasIndex("GrainKey", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_grain_messages_grain_key_sequence_number");

                    b.HasIndex("GrainKey", "TurnId")
                        .HasDatabaseName("ix_grain_messages_grain_key_turn_id");

                    b.ToTable("grain_messages", "actors");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.AgentDefinitions.AgentDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("ConnectToNavi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("connect_to_navi");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contract");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NodeConfigurations")
                        .HasColumnType("jsonb")
                        .HasColumnName("node_configurations");

                    b.Property<string>("ReactFlowData")
                        .HasColumnType("jsonb")
                        .HasColumnName("react_flow_data");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_agent_definitions_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_agent_definitions_user_id");

                    b.ToTable("agent_definitions", "agent_definitions");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_conversations_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversations_user_id");

                    b.ToTable("conversations", "conversations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_conversation_messages_conversation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_conversation_messages_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversation_messages_user_id");

                    b.ToTable("conversation_messages", "conversations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.ExternalApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("FieldsEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Provider");

                    b.ToTable("external_api_keys", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.OAuthProviderConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthorizationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<byte[]>("ClientIdEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ClientSecretEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ScopesJson")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("TokenUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserInfoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasFilter("\"Provider\" != 'Custom'");

                    b.ToTable("oauth_provider_configs", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.OAuthStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CodeVerifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("oauth_states", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.OAuthTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("oauth_tokens", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.SandboxCredentialMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BaseDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BasicAuthUsername")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialFieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HeaderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HeaderValueFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Raw");

                    b.Property<string>("HeaderValuePrefix")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ManagedByProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "BaseDomain", "HeaderName")
                        .IsUnique();

                    b.ToTable("sandbox_credential_mappings", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.SandboxCustomVariableEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSecret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.ToTable("sandbox_custom_variables", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.UserApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<byte[]>("EncryptedKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_api_keys", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("auth_type");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("endpoint");

                    b.Property<Guid>("McpServerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("mcp_server_configuration_id");

                    b.Property<Guid?>("OAuthTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("oauth_token_id");

                    b.Property<string>("TransportMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transport_mode");

                    b.HasKey("Id");

                    b.HasIndex("McpServerConfigurationId")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_http_configurations_mcp_server_configuration_id");

                    b.ToTable("http_configurations", "mcp");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpHeaderConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CredentialFieldType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("credential_field_type");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("HeaderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("header_name");

                    b.Property<byte[]>("HeaderValueEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("header_value_encrypted");

                    b.Property<Guid>("McpHttpConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("mcp_http_configuration_id");

                    b.HasKey("Id");

                    b.HasIndex("McpHttpConfigurationId")
                        .HasDatabaseName("ix_mcp_http_header_configurations_mcp_http_configuration_id");

                    b.HasIndex("McpHttpConfigurationId", "HeaderName")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_http_header_configurations_config_id_header_name");

                    b.ToTable("http_header_configurations", "mcp", t =>
                        {
                            t.HasCheckConstraint("ck_http_header_value_or_credential", "(header_value_encrypted IS NOT NULL AND credential_id IS NULL AND credential_field_type IS NULL) OR (header_value_encrypted IS NULL AND credential_id IS NOT NULL AND credential_field_type IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpOAuthConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthorizationEndpoint")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("authorization_endpoint");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_id");

                    b.Property<byte[]>("ClientSecretEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("client_secret_encrypted");

                    b.Property<Guid>("McpHttpConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("mcp_http_configuration_id");

                    b.Property<string>("RedirectUri")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("redirect_uri");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("scopes");

                    b.Property<string>("TokenEndpoint")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("token_endpoint");

                    b.HasKey("Id");

                    b.HasIndex("McpHttpConfigurationId")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_http_oauth_configurations_mcp_http_configuration_id");

                    b.ToTable("http_oauth_configurations", "mcp");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpServerConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("ConnectToNavi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("connect_to_navi");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transport_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mcp_server_configurations_user_id");

                    b.HasIndex("UserId", "IsEnabled")
                        .HasDatabaseName("ix_mcp_server_configurations_user_id_is_enabled");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_server_configurations_user_id_name");

                    b.ToTable("server_configurations", "mcp");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpStdioConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("arguments");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("command");

                    b.Property<Guid>("McpServerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("mcp_server_configuration_id");

                    b.Property<string>("PreExecScripts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("pre_exec_scripts");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("working_directory");

                    b.HasKey("Id");

                    b.HasIndex("McpServerConfigurationId")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_stdio_configurations_mcp_server_configuration_id");

                    b.ToTable("stdio_configurations", "mcp");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpStdioEnvironmentVariableEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CredentialFieldType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("credential_field_type");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<Guid>("McpStdioConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("mcp_stdio_configuration_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("McpStdioConfigurationId")
                        .HasDatabaseName("ix_mcp_stdio_env_vars_mcp_stdio_configuration_id");

                    b.HasIndex("McpStdioConfigurationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_stdio_env_vars_config_id_name");

                    b.ToTable("stdio_environment_variables", "mcp", t =>
                        {
                            t.HasCheckConstraint("ck_stdio_env_var_value_or_credential", "(value IS NOT NULL AND credential_id IS NULL AND credential_field_type IS NULL) OR (value IS NULL AND credential_id IS NOT NULL AND credential_field_type IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpToolInvocationLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClientId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("client_ip_address");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("InvokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoked_at");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("RequestParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_params");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_content");

                    b.Property<string>("SessionId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("session_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tool_name");

                    b.Property<string>("ToolProvider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tool_provider");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("InvokedAt")
                        .HasDatabaseName("ix_mcp_tool_invocation_logs_invoked_at");

                    b.HasIndex("ToolName")
                        .HasDatabaseName("ix_mcp_tool_invocation_logs_tool_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mcp_tool_invocation_logs_user_id");

                    b.HasIndex("ToolName", "InvokedAt")
                        .HasDatabaseName("ix_mcp_tool_invocation_logs_tool_name_invoked_at");

                    b.HasIndex("UserId", "InvokedAt")
                        .HasDatabaseName("ix_mcp_tool_invocation_logs_user_id_invoked_at");

                    b.ToTable("tool_invocation_logs", "mcp");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpTraceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClientIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("client_ip_address");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("JsonRpcId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("jsonrpc_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("method");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_body");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Method")
                        .HasDatabaseName("ix_mcp_traces_method");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_mcp_traces_started_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mcp_traces_user_id");

                    b.HasIndex("Method", "StartedAt")
                        .HasDatabaseName("ix_mcp_traces_method_started_at");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_mcp_traces_user_id_started_at");

                    b.ToTable("traces", "mcp");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Prompts.PromptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PromptType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_prompts_created_at");

                    b.HasIndex("PromptType")
                        .HasDatabaseName("ix_prompts_prompt_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_prompts_user_id");

                    b.ToTable("prompts", "prompts");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Scheduling.ScheduledJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatorEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("creator_email");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("creator_name");

                    b.Property<string>("CreatorUsername")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("creator_username");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("QuartzJobKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("quartz_job_key");

                    b.Property<string>("QuartzTriggerKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("quartz_trigger_key");

                    b.Property<DateTimeOffset?>("RunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at_utc");

                    b.Property<string>("ScheduleMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schedule_mode");

                    b.Property<Guid?>("TargetAgentDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_agent_definition_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Europe/Dublin")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_scheduled_jobs_is_enabled");

                    b.HasIndex("IsSystem")
                        .HasDatabaseName("ix_scheduled_jobs_is_system");

                    b.HasIndex("JobType")
                        .HasDatabaseName("ix_scheduled_jobs_job_type");

                    b.HasIndex("TargetType")
                        .HasDatabaseName("ix_scheduled_jobs_target_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_scheduled_jobs_user_id");

                    b.ToTable("scheduled_jobs", "scheduling");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Scheduling.ScheduledJobExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text")
                        .HasColumnName("error_details");

                    b.Property<string>("ExecutingNodeId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("executing_node_id");

                    b.Property<string>("OutputSummary")
                        .HasColumnType("text")
                        .HasColumnName("output_summary");

                    b.Property<string>("QuartzFireInstanceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("quartz_fire_instance_id");

                    b.Property<Guid>("ScheduledJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduled_job_id");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_source");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_scheduled_job_executions_correlation_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_scheduled_job_executions_status");

                    b.HasIndex("ScheduledJobId", "StartedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_scheduled_job_executions_job_started");

                    b.ToTable("scheduled_job_executions", "scheduling");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Scheduling.ScheduledJobPayloadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InputContext")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_context");

                    b.Property<Guid>("ScheduledJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduled_job_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_prompt");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledJobId")
                        .IsUnique()
                        .HasDatabaseName("ix_scheduled_job_payloads_scheduled_job_id");

                    b.ToTable("scheduled_job_payloads", "scheduling");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", "system");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.A2a.A2aServerHeaderConfigurationEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.A2a.A2aServerConfigurationEntity", "A2aServerConfiguration")
                        .WithMany("HeaderConfigurations")
                        .HasForeignKey("A2aServerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("A2aServerConfiguration");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationMessageEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpConfigurationEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Mcp.McpServerConfigurationEntity", "McpServerConfiguration")
                        .WithOne("HttpConfiguration")
                        .HasForeignKey("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpConfigurationEntity", "McpServerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServerConfiguration");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpHeaderConfigurationEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpConfigurationEntity", "McpHttpConfiguration")
                        .WithMany("HeaderConfigurations")
                        .HasForeignKey("McpHttpConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpHttpConfiguration");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpOAuthConfigurationEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpConfigurationEntity", "McpHttpConfiguration")
                        .WithOne("OAuthConfiguration")
                        .HasForeignKey("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpOAuthConfigurationEntity", "McpHttpConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpHttpConfiguration");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpStdioConfigurationEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Mcp.McpServerConfigurationEntity", "McpServerConfiguration")
                        .WithOne("StdioConfiguration")
                        .HasForeignKey("DonkeyWork.Agents.Persistence.Entities.Mcp.McpStdioConfigurationEntity", "McpServerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServerConfiguration");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpStdioEnvironmentVariableEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Mcp.McpStdioConfigurationEntity", "McpStdioConfiguration")
                        .WithMany("EnvironmentVariableConfigurations")
                        .HasForeignKey("McpStdioConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpStdioConfiguration");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Scheduling.ScheduledJobExecutionEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Scheduling.ScheduledJobEntity", "ScheduledJob")
                        .WithMany("Executions")
                        .HasForeignKey("ScheduledJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledJob");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Scheduling.ScheduledJobPayloadEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Scheduling.ScheduledJobEntity", "ScheduledJob")
                        .WithOne("Payload")
                        .HasForeignKey("DonkeyWork.Agents.Persistence.Entities.Scheduling.ScheduledJobPayloadEntity", "ScheduledJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledJob");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.A2a.A2aServerConfigurationEntity", b =>
                {
                    b.Navigation("HeaderConfigurations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpHttpConfigurationEntity", b =>
                {
                    b.Navigation("HeaderConfigurations");

                    b.Navigation("OAuthConfiguration");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpServerConfigurationEntity", b =>
                {
                    b.Navigation("HttpConfiguration");

                    b.Navigation("StdioConfiguration");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpStdioConfigurationEntity", b =>
                {
                    b.Navigation("EnvironmentVariableConfigurations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Scheduling.ScheduledJobEntity", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Payload");
                });
#pragma warning restore 612, 618
        }
    }
}
