// <auto-generated />
using System;
using DonkeyWork.Agents.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DonkeyWork.Agents.Persistence.Migrations
{
    [DbContext(typeof(AgentsDbContext))]
    [Migration("20260205083230_ConversationContentParts")]
    partial class ConversationContentParts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrchestrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("orchestration_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_conversations_created_at");

                    b.HasIndex("OrchestrationId")
                        .HasDatabaseName("ix_conversations_orchestration_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversations_user_id");

                    b.ToTable("conversations", "conversations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_conversation_messages_conversation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_conversation_messages_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversation_messages_user_id");

                    b.ToTable("conversation_messages", "conversations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.ExternalApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("FieldsEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Provider");

                    b.ToTable("external_api_keys", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.OAuthProviderConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("ClientIdEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ClientSecretEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("oauth_provider_configs", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.OAuthTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("oauth_tokens", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Credentials.UserApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<byte[]>("EncryptedKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_api_keys", "credentials");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Mcp.McpToolInvocationLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClientId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("client_ip_address");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("InvokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoked_at");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("RequestParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_params");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_content");

                    b.Property<string>("SessionId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("session_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tool_name");

                    b.Property<string>("ToolProvider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tool_provider");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("InvokedAt")
                        .HasDatabaseName("ix_mcp_tool_invocation_logs_invoked_at");

                    b.HasIndex("ToolName")
                        .HasDatabaseName("ix_mcp_tool_invocation_logs_tool_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mcp_tool_invocation_logs_user_id");

                    b.HasIndex("ToolName", "InvokedAt")
                        .HasDatabaseName("ix_mcp_tool_invocation_logs_tool_name_invoked_at");

                    b.HasIndex("UserId", "InvokedAt")
                        .HasDatabaseName("ix_mcp_tool_invocation_logs_user_id_invoked_at");

                    b.ToTable("tool_invocation_logs", "mcp");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_orchestrations_created_at");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_orchestrations_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orchestrations_user_id");

                    b.ToTable("orchestrations", "orchestrations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("interface");

                    b.Property<Guid>("OrchestrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("orchestration_id");

                    b.Property<Guid>("OrchestrationVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("orchestration_version_id");

                    b.Property<string>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StreamName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stream_name");

                    b.Property<int?>("TotalTokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens_used");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Interface")
                        .HasDatabaseName("ix_orchestration_executions_interface");

                    b.HasIndex("OrchestrationId")
                        .HasDatabaseName("ix_orchestration_executions_orchestration_id");

                    b.HasIndex("OrchestrationVersionId")
                        .HasDatabaseName("ix_orchestration_executions_orchestration_version_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_orchestration_executions_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orchestration_executions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orchestration_executions_user_id");

                    b.HasIndex("OrchestrationId", "StartedAt")
                        .HasDatabaseName("ix_orchestration_executions_orchestration_id_started_at");

                    b.ToTable("orchestration_executions", "orchestrations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationExecutionLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("log_level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NodeId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("node_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_orchestration_execution_logs_created_at");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("ix_orchestration_execution_logs_execution_id");

                    b.HasIndex("LogLevel")
                        .HasDatabaseName("ix_orchestration_execution_logs_log_level");

                    b.HasIndex("ExecutionId", "CreatedAt")
                        .HasDatabaseName("ix_orchestration_execution_logs_execution_id_created_at");

                    b.ToTable("orchestration_execution_logs", "orchestrations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationNodeExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FullResponse")
                        .HasColumnType("text")
                        .HasColumnName("full_response");

                    b.Property<string>("Input")
                        .HasColumnType("jsonb")
                        .HasColumnName("input");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("node_name");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("node_type");

                    b.Property<Guid>("OrchestrationExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("orchestration_execution_id");

                    b.Property<string>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("NodeType")
                        .HasDatabaseName("ix_orchestration_node_executions_node_type");

                    b.HasIndex("OrchestrationExecutionId")
                        .HasDatabaseName("ix_orchestration_node_executions_orchestration_execution_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_orchestration_node_executions_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orchestration_node_executions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orchestration_node_executions_user_id");

                    b.ToTable("orchestration_node_executions", "orchestrations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationVersionCredentialMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("OrchestrationVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("orchestration_version_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_orchestration_version_credential_mappings_credential_id");

                    b.HasIndex("OrchestrationVersionId")
                        .HasDatabaseName("ix_orchestration_version_credential_mappings_orchestration_version_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orchestration_version_credential_mappings_user_id");

                    b.HasIndex("OrchestrationVersionId", "NodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_orchestration_version_credential_mappings_version_node");

                    b.ToTable("orchestration_version_credential_mappings", "orchestrations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InputSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_schema");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("interface");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft");

                    b.Property<string>("NodeConfigurations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("node_configurations");

                    b.Property<Guid>("OrchestrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("orchestration_id");

                    b.Property<string>("OutputSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_schema");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ReactFlowData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("react_flow_data");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_orchestration_versions_created_at");

                    b.HasIndex("OrchestrationId")
                        .HasDatabaseName("ix_orchestration_versions_orchestration_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orchestration_versions_user_id");

                    b.HasIndex("OrchestrationId", "IsDraft")
                        .HasDatabaseName("ix_orchestration_versions_orchestration_id_is_draft");

                    b.ToTable("orchestration_versions", "orchestrations");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SuccessCriteria")
                        .HasColumnType("text")
                        .HasColumnName("success_criteria");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_milestones_due_date");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_milestones_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_milestones_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_milestones_user_id");

                    b.ToTable("milestones", "projects");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneFileReferenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("milestone_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneId")
                        .HasDatabaseName("ix_milestone_file_references_milestone_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_milestone_file_references_user_id");

                    b.ToTable("milestone_file_references", "projects");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("milestone_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneId")
                        .HasDatabaseName("ix_milestone_tags_milestone_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_milestone_tags_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_milestone_tags_user_id");

                    b.ToTable("milestone_tags", "projects");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.NoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("milestone_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notes_created_at");

                    b.HasIndex("MilestoneId")
                        .HasDatabaseName("ix_notes_milestone_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_notes_project_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notes_user_id");

                    b.ToTable("notes", "projects");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.NoteTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_note_tags_name");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_note_tags_note_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_note_tags_user_id");

                    b.ToTable("note_tags", "projects");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SuccessCriteria")
                        .HasColumnType("text")
                        .HasColumnName("success_criteria");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_projects_created_at");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_projects_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_projects_user_id");

                    b.ToTable("projects", "projects");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectFileReferenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_file_references_project_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_file_references_user_id");

                    b.ToTable("project_file_references", "projects");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_project_tags_name");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_tags_project_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_tags_user_id");

                    b.ToTable("project_tags", "projects");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.TodoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletionNotes")
                        .HasColumnType("text")
                        .HasColumnName("completion_notes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("milestone_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_todos_due_date");

                    b.HasIndex("MilestoneId")
                        .HasDatabaseName("ix_todos_milestone_id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_todos_priority");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_todos_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_todos_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todos_user_id");

                    b.ToTable("todos", "projects");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.TodoTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TodoId")
                        .HasColumnType("uuid")
                        .HasColumnName("todo_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_todo_tags_name");

                    b.HasIndex("TodoId")
                        .HasDatabaseName("ix_todo_tags_todo_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_tags_user_id");

                    b.ToTable("todo_tags", "projects");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Storage.FileShareEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxDownloads")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("FileId");

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("file_shares", "storage");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Storage.StoredFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("MarkedForDeletionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("stored_files", "storage");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", "system");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationEntity", "Orchestration")
                        .WithMany()
                        .HasForeignKey("OrchestrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orchestration");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationMessageEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationVersionEntity", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationExecutionEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationEntity", "Orchestration")
                        .WithMany()
                        .HasForeignKey("OrchestrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationVersionEntity", "OrchestrationVersion")
                        .WithMany("Executions")
                        .HasForeignKey("OrchestrationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orchestration");

                    b.Navigation("OrchestrationVersion");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationExecutionLogEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationExecutionEntity", "Execution")
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationNodeExecutionEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationExecutionEntity", "OrchestrationExecution")
                        .WithMany("NodeExecutions")
                        .HasForeignKey("OrchestrationExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrchestrationExecution");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationVersionCredentialMappingEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationVersionEntity", "OrchestrationVersion")
                        .WithMany("CredentialMappings")
                        .HasForeignKey("OrchestrationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrchestrationVersion");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationVersionEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationEntity", "Orchestration")
                        .WithMany("Versions")
                        .HasForeignKey("OrchestrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orchestration");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneFileReferenceEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneEntity", "Milestone")
                        .WithMany("FileReferences")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneTagEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneEntity", "Milestone")
                        .WithMany("Tags")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.NoteEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneEntity", "Milestone")
                        .WithMany("Notes")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("Notes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Milestone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.NoteTagEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.NoteEntity", "Note")
                        .WithMany("Tags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectFileReferenceEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("FileReferences")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectTagEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("Tags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.TodoEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneEntity", "Milestone")
                        .WithMany("Todos")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("Todos")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Milestone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.TodoTagEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Projects.TodoEntity", "Todo")
                        .WithMany("Tags")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Storage.FileShareEntity", b =>
                {
                    b.HasOne("DonkeyWork.Agents.Persistence.Entities.Storage.StoredFileEntity", "File")
                        .WithMany("Shares")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Conversations.ConversationEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationExecutionEntity", b =>
                {
                    b.Navigation("NodeExecutions");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Orchestrations.OrchestrationVersionEntity", b =>
                {
                    b.Navigation("CredentialMappings");

                    b.Navigation("Executions");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.MilestoneEntity", b =>
                {
                    b.Navigation("FileReferences");

                    b.Navigation("Notes");

                    b.Navigation("Tags");

                    b.Navigation("Todos");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.NoteEntity", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.ProjectEntity", b =>
                {
                    b.Navigation("FileReferences");

                    b.Navigation("Milestones");

                    b.Navigation("Notes");

                    b.Navigation("Tags");

                    b.Navigation("Todos");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Projects.TodoEntity", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DonkeyWork.Agents.Persistence.Entities.Storage.StoredFileEntity", b =>
                {
                    b.Navigation("Shares");
                });
#pragma warning restore 612, 618
        }
    }
}
